### PR TITLE
Add landing page

### PR DESCRIPTION
**Pull request by mgomez0**
**Adds:** 

- landing page and associated static resources (CSS, JS, images)

- nodemon config file to track static resources

- route to landing page in routes.js

**Modifies:** 

- Standardizes formatting with [Prettier](https://prettier.io/)

### CODE REVIEW

**Review by playlend — APPROVED** [review]
Everything looks good to me. The code looks great with Prettier plug-in.

**Review by Noah-Fields — APPROVED** [review]
Looks awesome Michael, great job

**Review by hpwonder — APPROVED** [review]
Looks good

**Comment by lanthenguyen1993** [comment]
looks good to me

**Pull request merged**
